# Generated by Django 4.2.16 on 2024-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_characteristicvalue_headline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='популярные товары')),
            ],
        ),
        migrations.CreateModel(
            name='SlideOnMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='товары для слайдера')),
            ],
        ),
        migrations.CreateModel(
            name='PopularProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='популярные товары')),
            ],
        ),
    ]
