# Generated by Django 4.2.16 on 2024-10-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_characteristic_comment_product_picturefordescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristicvalue',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
